LEVEL=../../../..

#
# Give the name of a library.  This will build a dynamic version.
#
LIBRARYNAME = analysis



#INC_DIR = ../
#CFLAGS=-c -Wall -I$(INC_DIR)
#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common